# Generated by Django 4.2.2 on 2023-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ali",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("data_criacao", models.DateField()),
                ("imagem", models.ImageField(upload_to="imagens")),
            ],
        ),
        migrations.CreateModel(
            name="Api",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("texto", models.TextField()),
                ("data_criacao", models.DateField()),
                ("imagem", models.ImageField(upload_to="imagens")),
            ],
        ),
    ]
