# Generated by Django 4.2.2 on 2023-06-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0002_ali_api"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=25, null="")),
            ],
        ),
        migrations.CreateModel(
            name="Cursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=25)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField()),
                ("imagem", models.ImageField(upload_to="imagens")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curso.categoria",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Ali",
        ),
        migrations.DeleteModel(
            name="Api",
        ),
        migrations.DeleteModel(
            name="Info",
        ),
    ]
