# Generated by Django 4.2.2 on 2023-06-18 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("curso", "0003_categoria_cursos_delete_ali_delete_api_delete_info"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cursos",
            new_name="Curso_Ali",
        ),
        migrations.CreateModel(
            name="Curso_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=25)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField()),
                ("imagem", models.ImageField(upload_to="imagens")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curso.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso_Api",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=25)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField()),
                ("imagem", models.ImageField(upload_to="imagens")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="curso.categoria",
                    ),
                ),
            ],
        ),
    ]
